### PR TITLE
Regenerate gemspec for version 0.3.0

### PR DESCRIPTION
**Pull request by onerinas**

### CODE REVIEW

**Comment by onerinas** [comment]
@kristianmandrup Here is my email `onerinas@gmail.com` incase you want me to give write access / add to rubygems so that I can update directly.

**Comment by kristianmandrup** [comment]
I'm offline on skiing trip in Italy

**Comment by onerinas** [comment]
Enjoy your trip :)

**Comment by onerinas** [comment]
@kristianmandrup Had a chance to look in to this? (btw how was your skiing trip 😃 )

**Pull request merged**
